name: Make Labels and Priors (SUTAM)

on:
  workflow_dispatch:
    inputs:
      persist:
        description: "Çıktılar nasıl saklansın?"
        type: choice
        options: [artifact, commit, none]
        default: artifact

permissions:
  contents: write
  actions: read

jobs:
  make_labels_and_priors:
    runs-on: ubuntu-latest

    env:
      TZ: "America/Los_Angeles"
      DATA_DIR: .   # ÇÖZÜM A: kök dizin
      OUT_FILE: sf_crime_grid_full_labeled.parquet
      OUT_ZIP:  fr-crime-outputs-parquet.zip

    steps:
      - name: Checkout repo (with LFS)
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Show workspace (quick diag)
        run: |
          set -e
          echo "PWD=$(pwd)"
          ls -lah
          echo "---- Top-level files ----"
          /usr/bin/find . -maxdepth 1 -type f -printf "%p\t%k KB\n" | sort || true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          set -e
          python -m pip install -U pip
          pip install pandas pyarrow numpy

      - name: Detect input parquet & optional files
        id: detect
        run: |
          set -euo pipefail
          # Girdi (fr_crime_09.parquet) otomatik tespit (kökte olmalı ama yine de sağlam alalım)
          INPUT="$(
            /usr/bin/find "${DATA_DIR}" -maxdepth 2 -type f -name 'fr_crime_09.parquet' -print -quit
          )"
          if [ -z "${INPUT}" ]; then
            echo "❌ fr_crime_09.parquet bulunamadı."
            exit 1
          fi
          echo "✅ INPUT=${INPUT}"
          echo "input=${INPUT}" >> "$GITHUB_OUTPUT"

          # Opsiyonel ek dosyalar (varsa eklenecek)
          RH="$(
            /usr/bin/find "${DATA_DIR}" -maxdepth 2 -type f -name 'risky_hours.parquet' -print -quit
          )" || true
          MET="$(
            /usr/bin/find "${DATA_DIR}" -maxdepth 2 -type f -name 'metrics_stacking_ohe.parquet' -print -quit
          )" || true

          [ -n "${RH}" ]  && echo "risky_hours=${RH}" >> "$GITHUB_OUTPUT"
          [ -n "${MET}" ] && echo "metrics=${MET}"   >> "$GITHUB_OUTPUT"

          echo "---- Detect summary ----"
          echo "INPUT: ${INPUT}"
          echo "RISKY: ${RH:-<none>}"
          echo "METRICS: ${MET:-<none>}"

      - name: Generate labels + priors + package
        run: |
          set -euo pipefail
          INPUT="${{ steps.detect.outputs.input }}"
          OUT_PQ="${DATA_DIR}/${OUT_FILE}"
          OUT_ZIP="${DATA_DIR}/${OUT_ZIP}"

          # Opsiyonel argüman dizisi
          EXTRA_ARGS=()
          if [ -n "${{ steps.detect.outputs.risky_hours || '' }}" ]; then
            EXTRA_ARGS+=( --risky-hours "${{ steps.detect.outputs.risky_hours }}" )
          fi
          if [ -n "${{ steps.detect.outputs.metrics || '' }}" ]; then
            EXTRA_ARGS+=( --metrics     "${{ steps.detect.outputs.metrics }}" )
          fi

          echo "▶️  Running make_labels_and_priors_xl.py ..."
          python make_labels_and_priors_xl.py \
            --input      "${INPUT}" \
            --out        "${OUT_PQ}" \
            --tz         America/Los_Angeles \
            --no-full-grid \
            --out-dir     "${DATA_DIR}" \
            --package-zip "${OUT_ZIP}" \
            "${EXTRA_ARGS[@]}"

          echo "---- Outputs ----"
          ls -lh "${OUT_PQ}" || true
          ls -lh "${OUT_ZIP}" || true

      - name: Upload artifact (if selected)
        if: ${{ github.event.inputs.persist == 'artifact' }}
        uses: actions/upload-artifact@v4
        with:
          name: fr-crime-outputs-parquet
          path: |
            ${{ env.DATA_DIR }}/${{ env.OUT_FILE }}
            ${{ env.DATA_DIR }}/${{ env.OUT_ZIP }}
          if-no-files-found: error
          retention-days: 14

      - name: Commit outputs (if selected)
        if: ${{ github.event.inputs.persist == 'commit' }}
        run: |
          set -e
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add "${DATA_DIR}/${OUT_FILE}" || true
          git add "${DATA_DIR}/${OUT_ZIP}"  || true

          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          git commit -m "chore: add ${OUT_FILE} and ${OUT_ZIP} (auto)"
          git push origin HEAD:${GITHUB_REF##*/}

      - name: Job summary
        run: |
          set -e
          echo "## Make Labels and Priors — Özet" >> "$GITHUB_STEP_SUMMARY"
          echo "" >> "$GITHUB_STEP_SUMMARY"
          echo "- Input: \`${{ steps.detect.outputs.input }}\`" >> "$GITHUB_STEP_SUMMARY"
          if [ -n "${{ steps.detect.outputs.risky_hours || '' }}" ]; then
            echo "- risky_hours: \`${{ steps.detect.outputs.risky_hours }}\`" >> "$GITHUB_STEP_SUMMARY"
          fi
          if [ -n "${{ steps.detect.outputs.metrics || '' }}" ]; then
            echo "- metrics: \`${{ steps.detect.outputs.metrics }}\`" >> "$GITHUB_STEP_SUMMARY"
          fi
          echo "- Output Parquet: \`${{ env.DATA_DIR }}/${{ env.OUT_FILE }}\`" >> "$GITHUB_STEP_SUMMARY"
          echo "- Output ZIP: \`${{ env.DATA_DIR }}/${{ env.OUT_ZIP }}\`" >> "$GITHUB_STEP_SUMMARY"
