name: Make Labels + Train (SUTAM)

on:
  workflow_dispatch:
    inputs:
      persist:
        description: "Çıktılar nasıl saklansın?"
        type: choice
        options: [artifact, commit, none]
        default: artifact
      granularity:
        description: "Hangi model(ler) eğitilsin?"
        type: choice
        options: [hourly, 8h, 1d, all]
        default: hourly
      balanced:
        description: "Saatlik modeli SMOTE/downsample ile dengele"
        type: boolean
        default: false

permissions:
  contents: write
  actions: read

jobs:
  build_and_train:
    runs-on: ubuntu-latest
    env:
      TZ: "America/Los_Angeles"
      DATA_DIR: .
      OUT_FILE: sf_crime_grid_full_labeled.parquet
      OUT_ZIP:  fr-crime-outputs-parquet.zip

    steps:
      - name: Checkout repo (with LFS)
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Show workspace
        run: |
          echo "PWD=$(pwd)"
          ls -lah

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            # Minimal ama blok/smote için de yeterli
            pip install numpy pandas pyarrow tqdm scipy \
                        scikit-learn xgboost lightgbm imbalanced-learn \
                        joblib matplotlib
          fi

      - name: Detect input parquet & optional files
        id: detect
        run: |
          set -euo pipefail

          prefer_10="$(
            /usr/bin/find "${DATA_DIR}" -maxdepth 2 -type f -name 'fr_crime_10.parquet' -print -quit
          )" || true
          prefer_09="$(
            /usr/bin/find "${DATA_DIR}" -maxdepth 2 -type f -name 'fr_crime_09.parquet' -print -quit
          )" || true

          if [ -n "${prefer_10}" ]; then
            INPUT="${prefer_10}"
          elif [ -n "${prefer_09}" ]; then
            INPUT="${prefer_09}"
          else
            echo "❌ fr_crime_10.parquet / fr_crime_09.parquet bulunamadı."
            exit 1
          fi

          echo "input=${INPUT}" >> "$GITHUB_OUTPUT"
          echo "✅ INPUT=${INPUT}"

          RH="$(
            /usr/bin/find "${DATA_DIR}" -maxdepth 2 -type f \( -name 'risk_hourly.parquet' -o -name 'risky_hours.parquet' \) -print -quit
          )" || true
          MET="$(
            /usr/bin/find "${DATA_DIR}" -maxdepth 2 -type f -name 'metrics_stacking_ohe.parquet' -print -quit
          )" || true

          if [ -n "${RH}" ]; then echo "risky_hours=${RH}" >> "$GITHUB_OUTPUT"; fi
          if [ -n "${MET}" ]; then echo "metrics=${MET}"     >> "$GITHUB_OUTPUT"; fi

          echo "---- Detect summary ----"
          echo "INPUT: ${INPUT}"
          echo "RISKY: ${RH:-<none>}"
          echo "METRICS: ${MET:-<none>}"

      - name: Build labels + priors (+ package)
        run: |
          set -euo pipefail
          INPUT="${{ steps.detect.outputs.input }}"
          OUT_PQ="${DATA_DIR}/${OUT_FILE}"
          OUT_ZIP="${DATA_DIR}/${OUT_ZIP}"

          EXTRA_ARGS=()
          if [ -n "${{ steps.detect.outputs.risky_hours }}" ]; then
            EXTRA_ARGS+=( --risky-hours "${{ steps.detect.outputs.risky_hours }}" )
          fi
          if [ -n "${{ steps.detect.outputs.metrics }}" ]; then
            EXTRA_ARGS+=( --metrics     "${{ steps.detect.outputs.metrics }}" )
          fi

          echo "▶️  Running make_labels_and_priors_xl.py ..."
          python -u make_labels_and_priors_xl.py \
            --input       "${INPUT}" \
            --out         "${OUT_PQ}" \
            --tz          America/Los_Angeles \
            --out-dir     "${DATA_DIR}" \
            --package-zip "${OUT_ZIP}" \
            "${EXTRA_ARGS[@]}"

          test -s "${OUT_PQ}" || { echo "❌ Output parquet yok: ${OUT_PQ}"; exit 1; }
          [ -f "${DATA_DIR}/y_label_stats.csv" ] && { echo "Y_label stats:"; cat "${DATA_DIR}/y_label_stats.csv" || true; }

          echo "---- Outputs ----"
          ls -lh "${OUT_PQ}" || true
          ls -lh "${OUT_ZIP}" || true

      # ---- 8H / 1D için agregasyon
      - name: Aggregate to 8H and/or 1D
        if: ${{ github.event.inputs.granularity == '8h' || github.event.inputs.granularity == '1d' || github.event.inputs.granularity == 'all' }}
        run: |
          set -euo pipefail
          MAKE_8H=false
          MAKE_1D=false
          if [ "${{ github.event.inputs.granularity }}" = "8h" ] || [ "${{ github.event.inputs.granularity }}" = "all" ]; then
            MAKE_8H=true
          fi
          if [ "${{ github.event.inputs.granularity }}" = "1d" ] || [ "${{ github.event.inputs.granularity }}" = "all" ]; then
            MAKE_1D=true
          fi

          ARGS=()
          $MAKE_8H && ARGS+=( --make-8h )
          $MAKE_1D && ARGS+=( --make-1d )

          echo "▶️  aggregate_windows.py ${ARGS[*]}"
          python -u aggregate_windows.py "${ARGS[@]}"

          ls -lh sf_crime_grid_8h.parquet || true
          ls -lh sf_crime_grid_1d.parquet || true

      # ---- Saatlik eğitim: balanced seçimine göre script
      - name: Train hourly model (balanced or vanilla)
        if: ${{ github.event.inputs.granularity == 'hourly' || github.event.inputs.granularity == 'all' }}
        run: |
          set -euo pipefail
          if [ "${{ github.event.inputs.balanced }}" = "true" ]; then
            echo "▶️  train_hourly_model_balanced.py"
            python -u train_hourly_model_balanced.py
          else
            echo "▶️  train_hourly_model.py"
            python -u train_hourly_model.py
          fi

      # ---- 8H eğitim
      - name: Train 8H model
        if: ${{ github.event.inputs.granularity == '8h' || github.event.inputs.granularity == 'all' }}
        run: |
          set -euo pipefail
          echo "▶️  train_block_model.py (8H)"
          python -u train_block_model.py  # default 8H dosyasını okuyor (sf_crime_grid_8h.parquet)

      # ---- 1D eğitim
      - name: Train 1D model
        if: ${{ github.event.inputs.granularity == '1d' || github.event.inputs.granularity == 'all' }}
        run: |
          set -euo pipefail
          echo "▶️  train_block_model.py (1D)"
          # train_block_model.py içinde DATA_PATH'i CLI argümanına çevirmediysen
          # küçük bir hack: dosyayı kopyalayıp isim verelim:
          cp sf_crime_grid_1d.parquet sf_crime_grid_8h.parquet
          python -u train_block_model.py
          # ardından geri al:
          git checkout -- sf_crime_grid_8h.parquet || true

      - name: Upload artifacts (if selected)
        if: ${{ github.event.inputs.persist == 'artifact' }}
        uses: actions/upload-artifact@v4
        with:
          name: sutam-model-outputs
          path: |
            ${{ env.DATA_DIR }}/${{ env.OUT_FILE }}
            ${{ env.DATA_DIR }}/${{ env.OUT_ZIP }}
            ${{ env.DATA_DIR }}/y_label_stats.csv
            # Agregasyon çıktıları (varsa)
            sf_crime_grid_8h.parquet
            sf_crime_grid_1d.parquet
            # Modeller & raporlar
            models/*.joblib
            reports/*.json
            reports/*.csv
          if-no-files-found: warn
          retention-days: 14

      - name: Commit outputs (if selected)
        if: ${{ github.event.inputs.persist == 'commit' }}
        run: |
          set -e
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add "${DATA_DIR}/${OUT_FILE}" || true
          git add "${DATA_DIR}/${OUT_ZIP}"  || true
          [ -f "${DATA_DIR}/y_label_stats.csv" ] && git add "${DATA_DIR}/y_label_stats.csv" || true
          [ -f sf_crime_grid_8h.parquet ] && git add sf_crime_grid_8h.parquet || true
          [ -f sf_crime_grid_1d.parquet ] && git add sf_crime_grid_1d.parquet || true
          git add models/*.joblib 2>/dev/null || true
          git add reports/* 2>/dev/null || true

          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          git commit -m "chore: labels+priors, (hourly/8h/1d) training & reports"
          git push origin "${GITHUB_REF_NAME:-$(git rev-parse --abbrev-ref HEAD)}"

      - name: Job summary
        run: |
          set -e
          {
            echo "## Make Labels + Train — Özet"
            echo ""
            echo "- Input: \`${{ steps.detect.outputs.input }}\`"
            echo "- Granularity: \`${{ github.event.inputs.granularity }}\`"
            echo "- Balanced(hourly): \`${{ github.event.inputs.balanced }}\`"
            if [ -n "${{ steps.detect.outputs.risky_hours }}" ]; then
              echo "- risky_hours: \`${{ steps.detect.outputs.risky_hours }}\`"
            fi
            if [ -n "${{ steps.detect.outputs.metrics }}" ]; then
              echo "- metrics: \`${{ steps.detect.outputs.metrics }}\`"
            fi
            echo "- Output Parquet: \`${{ env.DATA_DIR }}/${{ env.OUT_FILE }}\`"
            echo "- Output ZIP: \`${{ env.DATA_DIR }}/${{ env.OUT_ZIP }}\`"
            if [ -f "${{ env.DATA_DIR }}/y_label_stats.csv" ]; then
              echo ""
              echo "### Y_label dağılımı"
              tail -n +1 "${{ env.DATA_DIR }}/y_label_stats.csv"
            fi
            echo ""
            ls -lh models 2>/dev/null || true
            ls -lh reports 2>/dev/null || true
          } >> "$GITHUB_STEP_SUMMARY"
